language: python
python: "3.6"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install coveralls

script: nox --session "test"

after_success:
  - coveralls
