# Python CircleCI 2.0 configuration file for VLNM
#
version: 2
jobs:
  build:
    docker:
      - image: googleapis/nox:0.18.2
    steps:
      - checkout
      - run:
          name: Upgrade nox
          command: |
            pip install --upgrade nox
      - run:
          name: Test
          command: |
            nox --session test
