dataframe:
  formatters:
      float64: '{:.03f}'
  index: yes
  dtypes:
      speaker: str
      vowel: str
before: |
  import matplotlib
  matplotlib.use("agg")
  import pandas as pd
  from vlnm import normalize
path: '{tmpdir}'
